config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  
  resources :blogs
 

 
  resources :users, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show]
  
  resources :posts do

  end
  
  
  resources :calenders
  
  
  root 'posts#index'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/calender.rb
class Calender < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:validatable
 mount_uploader :image, ImageUploader
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end
  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    Blog.create(blog_parameter)
    redirect_to blogs_path
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!

    def create
      if Entry.where(user_id: current_user.id, room_id: params[:message][:room_id]).present?
        @message = Message.new(message_params)
        if @message.save
            redirect_to "/rooms/#{@message.room_id}"
        end
      else
        redirect_back(fallback_location: root_path)
      end
    end
    
    private 
    def message_params
        params.require(:message).permit(:user_id, :body, :room_id).merge(user_id: current_user.id)
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
        @posts= Post.all
    end

    def new
        @post = Post.new
      end
    
    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

    def show
        @post = Post.find(params[:id])
      end

    def edit
        @post = Post.find(params[:id])
      end
    
    def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
      end

      private
    def post_params
        params.require(:post).permit(:rugby_title, :rugby_content, :image)
      end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!
    
    def create
      @room = Room.create
      Entry.create(room_id: @room.id, user_id: current_user.id)
      Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
      redirect_to "/rooms/#{@room.id}"
    end
  
    def show
     
      @room = Room.find(params[:id])
      if Entry.where(user_id: current_user.id, room_id: @room.id).present?
        @messages = @room.messages.all
        @message = Message.new
        @entries = @room.entries
      else
        redirect_back(fallback_location: root_path)
      end
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
      @msg =""
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
    end

    if @isRoom != true
        @room = Room.new
        @entry = Entry.new
    end

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

    <div class="title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
      <div class="time">
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time %>
    </div>
  
    <div class="content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
  
  
    <div class="submit">
      <%= form.submit %>
    </div>
  
  <% end %>
  

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>自分の日記</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog.id) %></td>
        <td><%= link_to 'Destroy',blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日記をかく', new_blog_path %>

<%= month_calendar events: @blogs do |date, blogs| %>
  <%= date.day %>

  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog %>
    </div>
  <% end %>
<% end %>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

    <div class="title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
      <div class="time">
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time %>
    </div>
  
    <div class="content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
  
  
    <div class="submit">
      <%= form.submit %>
    </div>
  
  <% end %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>時間</strong>
  <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  
    <%= f.text_field :rugby_title, :size => "100x1000" %> 
  
    <%= f.file_field :image %>
    <%= f.submit "編集" %>
  <% end %>

 
   

app/views/posts/index.html.erb
<h1></h1>
<h3></h3>
<div class="posts-container">
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
  <%= link_to "新規投稿へ", new_post_path %>
  
<% end %>
  <% @posts.each do |t| %>
    
    <div class="post">
    <%= t.user.email %>
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.rugby_title %>
      <%= t.rugby_content %>
      <%= link_to "詳細へ", post_path(t.id) %>
      <%= link_to "編集する", edit_post_path(t.id) %>
      <%= button_to "削除する", post_path(t.id), method: :delete %>
      <%= link_to t.user.name, user_path(t.user.id) %> 
     <%= t.user.email %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1></h1>
<h3>新規投稿</h3>
<%= form_for @post do |f| %>




 <div class="field">
   
    <%= f.text_area :rugby_title, :size => "50x5" %>
 </div>

  

  <div class="field">
    <%= f.label :写真を追加 %>
    <%= f.file_field :image %>
  </div>



  <%= f.submit "投稿" %>
<% end %>

<%= link_to "一覧に戻る", posts_path %>

app/views/posts/show.html.erb
<h1></h1>
<h3>投稿詳細</h3>
<div class="post">
  <p><%= @post.rugby_title %></p>
  <p><%= @post.rugby_content %></p>
  <p><%= @post.created_at %></p>
</div>

<%= link_to "投稿一覧に戻る", posts_path %>
<%= link_to "編集する", edit_post_path(@post.id) %>

app/views/rooms/show.html.erb
<div class="user-in">
<% @entries.each do |e| %>
    <h3><strong><a href="/users/<%= e.user.id %>"><%= e.user.name%></a></strong></h3>
<% end %>
<p></p>
</div>

<div class="dmMain">
    <% @messages.each do |m| %>
        <strong><%= m.body %></strong>
        <small><%= m.user.name %>さん</small><hr>
    <% end %>

    <%= form_for @message do |f| %>
    <%= f.text_field :body, :placeholder => "メッセージを入力して下さい" , :size => 100 %>
    <%= f.hidden_field :room_id, :value => @room.id %>
    <br>
    <%= f.submit "送信" %>
    <% end %>
</div>

<%= link_to "ユーザー一覧に戻る", users_path %>