config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  
  resources :blogs
 

 
  resources :users, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show]
  
  resources :posts do

  end
  
  
  resources :calenders
  
  
  root 'posts#index'

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:validatable
 mount_uploader :image, ImageUploader
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
      @msg =""
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
    end

    if @isRoom != true
        @room = Room.new
        @entry = Entry.new
    end

    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/detail.html.erb
<h1>ユーザー詳細ページ</h1>

<div class="user-in">
<h2><%= @user.email %></h2>

<% if @user.id == current_user.id %>
    <%= @msg %>
<% else %>
    <% if @isRoom == true %>
        <%= link_to 'DMへ', room_path(@roomId) %>
    <% else %>
        <%= form_for @room do |f| %>
            <%= fields_for @entry do |e|%>
                <% e.hidden_field :user_id, value: @user.id %>
            <% end %>
        <%= f.submit "DMを開始する"%>
        <% end %>
    <% end %>
<% end %>
</div>


<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/users/index.html.erb
<h1></h1>
<h2>ユーザー一覧</h2>

<% if user_signed_in? %>
    <h2><%= current_user.name %>でログインしています</h2>
   
    <% number = 1%>
    <div class="flex">
        <% @users.each do |u| %>
        <div class="user-in">
            <p>プロフィール No.<%= number %></p>
            <p><%= u.name %>さん</p>
            <p><%= link_to 'ユーザーページへ', user_path(u.id) %></p>
        </div>
        <% number += 1 %>
        <% end %>
    </div>

<% else %>
  <%= link_to "SignUp", new_user_registration_path %>
  <br>
  <%= link_to "SignIn", new_user_session_path %>
<% end %>

app/views/users/show.html.erb
<h1></h1>
<p>名前 : <%= @user.name %></p>
<p>自己紹介 : <%= @user.profile %></p>
<%= image_tag @user.image_url, size: "250x200" if @user.image? %>
<% if current_user.id == @user.id %>
  <%= link_to "プロフィールを編集する", edit_user_registration_path %>
<% end %>
<div class="user-in">


<% if @user.id == current_user.id %>
    <%= @msg %>
<% else %>
    <% if @isRoom == true %>
        <%= link_to 'DMへ', room_path(@roomId) %>
    <% else %>
        <%= form_for @room do |f| %>
            <%= fields_for @entry do |e|%>
                <% e.hidden_field :user_id, value: @user.id %>
            <% end %>
        <%= f.submit "DMを開始する"%>
        <% end %>
    <% end %>
<% end %>
</div>




<% @user.posts.each do |t| %>
    <%= t.user.email %>
    <%= t.rugby_title %>
    <%= t.rugby_content %>
    
<% end %>

<%= link_to "ユーザー一覧へ", users_path %>
<%= link_to "新規投稿へ", posts_path %>
<%= link_to "投稿一覧に戻る", posts_path %>